USE ENDPOINTS;
GO
CREATE OR ALTER PROCEDURE addProduct2(@ID VARCHAR(255),@PNAME VARCHAR(255),@PRICE VARCHAR(255))
AS
BEGIN
    INSERT INTO Product(ID,PNAME,PRICE) 
    VALUES(@ID,@PNAME,@PRICE)
   

END;